I23 splash screen
Tinytown/tinytown-react-app pull request #29
Opened 2020-09-05 00:56 UTC by alfalcon90

fixes #23

2020-09-05 17:37 UTC, abdih commented
I'm a bit confused. I have these questions:

1. Why do we have 2 splash screens currently? (our own custom one and this third-party library's).
2. Where do we imagine the twitter authorization button appearing?
3. Have we seriously considered the trade-offs of using a third-party splash screen with respect to developer flexibility moving forward?

2020-09-05 17:38 UTC, abdih requested changes
I'm not technically requesting changes yet, but marking this to block merging until we resolve the questions I've put forth

2020-09-05 19:09 UTC, abdih commented
> I'm a bit confused. I have these questions:
> 
> 1. Why do we have 2 splash screens currently? (our own custom one and this third-party library's).
> 2. Where do we imagine the twitter authorization button appearing?
> 3. Have we seriously considered the trade-offs of using a third-party splash screen with respect to developer flexibility moving forward?

we synched about this offline.

the summary is that, the current splash screen is simply a temporary page for the twitter authorization button, and the splash screen itself is simply something that will appear and then disappear.

please see the following for a more detailed understanding of the app's flow: https://www.figma.com/proto/6HJ2ieYnB09P5eKdVl0a0c/Tinytown-MVP?node-id=0%3A1

2020-09-05 19:09 UTC, abdih approved these changes

2020-09-14 05:17 UTC, keedyc commented on App.js
>        <Splash></Splash>
@alfalcon90, if we don't plan to have any elements within `<Splash></Splash>`, it might be more idiomatic to use a single `<Splash />` tag. That mostly just a matter of style, though. This PR looks good to me 👍

2020-09-14 05:19 UTC, keedyc approved these changes

2020-09-14 16:04 UTC, alfalcon90 commented on App.js
>        <Splash></Splash>
I'll change it. This is the old Splash screen that's just a placeholder for the Twitter Sign-In button right now. It'll probably go away in the near future.

2020-09-14 16:16 UTC, merged