Add Style Variables
Tinytown/tinytown-react-app pull request #30
Opened 2020-09-05 01:00 UTC by alfalcon90

fixes #20

2020-09-06 18:16 UTC, abdih commented on App.js
> +import { TYPOGRAPHY, COLORS } from './frontend/styles'
don't need capitalization on consts.

2020-09-13 19:54 UTC, abdih requested changes
some nit-picky remarks.

2020-09-13 19:54 UTC, abdih commented on frontend/styles/color.js
> +// BLUES
I don't think these comments are necessary given the grouping of blocks already.

2020-09-13 19:54 UTC, abdih commented on CONTRIBUTING.md
> +feature/23-av-splash-screen
the `i` before the number may be useful here, since in the future, we may switch to a different ticket manager, say JIRA, which might overlap with these numbers. we would be able to distinguish by the ticket manager's prefix (e.g., AL-XX or iXX)

2020-09-13 19:54 UTC, abdih commented on CONTRIBUTING.md
> +feature/23-av-splash-screen
of course we can simply assume that if there's no prefix, then it's automatically GitHub. in which case, leaving this as is is fine.

2020-09-13 19:54 UTC, abdih commented on frontend/styles/index.js
> +  shapes,
I don't think we need separate name-spaces for the values (e.g., `justWhite` isn't going to be from anywhere but `colors` and `elevHairline` or `elevGray1` isn't going to be anywhere but `shapes`), so we can just spread these:

```suggestion
  ...colors,
  ...typography,
  ...shapes,
```

2020-09-13 19:54 UTC, abdih commented on frontend/styles/shapes.js
> +export const smRadius = 4;
maybe the noun first then the modifier/adjective, in the spirit of BEM css convention? so, `radiusSm` in this case

2020-09-13 21:10 UTC, alfalcon90 commented on frontend/styles/color.js
> +// BLUES
I think this is good to keep for future-proofing sake. This list will grow quite a bit down the road, with each color getting 10 variations: 50, 100, 200 ... 800, 900.

2020-09-13 21:11 UTC, alfalcon90 commented on CONTRIBUTING.md
> +feature/23-av-splash-screen
Adding a prefix sounds good to me.

2020-09-14 00:08 UTC, abdih approved these changes

2020-09-14 05:32 UTC, keedyc approved these changes
Aside from that little chance to avoid some redundancy, everything looks good 👍

2020-09-14 05:32 UTC, keedyc commented on frontend/styles/shapes.js
> +export const elevGray5 = {
Each color of the elevation 5 shape currently has this styling: 

```
shadowOffset: {
    width: 0,
    height: 6,
  },
  shadowOpacity: 0.5,
  shadowRadius: 7.49,

  elevation: 12,
```

In case we want to change that style in the future, it might help to extract it into a constant like `elev5` that we can include in the color-specific styles like so:

```
export const elevGray5 = {
  shadowColor: colors.asphaltGray,
  ...elev5,
};
```

2020-09-14 14:58 UTC, tinytown-admin commented on frontend/styles/shapes.js
> +export const elevGray5 = {
Good call. I'll add this today.

2020-09-14 14:59 UTC, alfalcon90 commented on frontend/styles/shapes.js
> +export const elevGray5 = {
Good call. I'll do this today.

2020-09-14 16:38 UTC, merged