i19: Add Marker for Current User Location
Tinytown/tinytown-react-app pull request #31
Opened 2020-09-05 22:06 UTC by abdih

fixes #19 

Note: From the corresponding asset zip, chose the default, which I believe is smallest dimension (we easily have the option of using 2 and 3x the current size): https://www.figma.com/file/6HJ2ieYnB09P5eKdVl0a0c/Tinytown-MVP?node-id=42%3A4500

2020-09-06 19:21 UTC, alfalcon90 commented
- I organized the images and icons under the assets folder.
- I added a new svg folder for icons that's structured similarly to the styles one.
- I added a high-density user marker icon

- [ ] Add rotation to user marker icon based on phone's orientation

2020-09-07 00:36 UTC, alfalcon90 requested changes
LGTM. Just need to add rotation based on device orientation.

2020-09-14 06:10 UTC, keedyc commented
This is really cool, @abdih!

I just ran into one oddity while trying it. When I click **Go to my location** while on Xcode's simulator, I get this error:

```
TypeError: null is not an object (evaluating '_this2.state.userLocation.longitude')

Geolocation.getCurrentPosition$argument_0
    index.js:147:32
```

Line 147 of index.js is part of a call to `this.setState`. It seems that `userLocation` is still null when this happens:
```
cameraCoordinates: [this.state.userLocation.longitude, this.state.userLocation.latitude],
```

I wonder whether something is strange in my setup. Fortunately, commenting out line 147 offered a temporary workaround so I could see this in action 😅

2020-09-20 19:41 UTC, abdih commented on frontend/mapbox/index.js
> +    }, 200, {trailing: false})
200 is arbitrary. might need tweaking in the future.

2020-09-20 23:59 UTC, alfalcon90 approved these changes

2020-09-21 02:09 UTC, abdih commented
thanks @alfalcon90 for the approval. now awaiting at least 1 more approval from @keedyc or @jamullan for the code perspective.

2020-09-26 19:28 UTC, merged

2020-09-27 00:47 UTC, keedyc commented on frontend/mapbox/index.js
> +      const latitudeChanged = this.state.userLocation ? Math.abs(latitude - this.state.userLocation.latitude) > coordinateThreshold : true;
I don't know that it's necessary, but I could imagine extracting this logic into its own `locationHasChanged` function, much like `cameraHasMoved`.

2020-09-27 00:56 UTC, keedyc commented on frontend/mapbox/index.js
> +    return Math.abs(coords.latitude - otherCoords.latitude > coordinateThreshold) || Math.abs(coords.longitude - otherCoords.longitude > coordinateThreshold);
It might be a bit more readable if we were to break up this one-liner. For example:
```
const cameraLatMoved = Math.abs(coords.latitude - otherCoords.latitude > coordinateThreshold);
const cameraLongMoved = Math.abs(coords.longitude - otherCoords.longitude > coordinateThreshold);
return cameraLatMoved || cameraLongMoved;
```

I also wonder whether we could reuse this function to avoid having similar math elsewhere. As one example, `updateLocation` also uses comparisons like `Math.abs(old.lat - new.lat > threshold)`.

2020-09-27 01:04 UTC, keedyc commented on frontend/mapbox/index.js
> +      the landscape view here is  e to me not knowing a better alternative to ensure map takes full page size.
Seems this was deleted on accident 😅

2020-09-27 01:13 UTC, keedyc commented on frontend/mapbox/index.js
> +                visible={haveLocationPermission}
Since `haveLocationPermission` is required to render this, could we use `true` instead of reusing the variable for this and the next line, like so?
```
visible={true}
animate={true}
```