Feature/i41 av project structure
Tinytown/tinytown-react-app pull request #46
Opened 2020-09-24 05:39 UTC by alfalcon90

Fixes #41 

Leaving as a draft for now to get feedback.

TODO
- [ ] Write scripts for importing svg files

2020-09-26 19:09 UTC, abdih requested changes

2020-09-26 19:09 UTC, abdih commented on src/screens/mapbox/index.js
> +      isMapLoading: false, // axiom: loading only applies to an existing map
I don't think this is used, so we can remove it.

2020-09-26 19:09 UTC, abdih commented on src/screens/mapbox/index.js
> +          console.log('doing first time go to location update');
please remove debugging logs.

2020-09-26 19:09 UTC, abdih commented on src/screens/mapbox/index.js
> +                styleURL={'mapbox://styles/alfalcon/cka1xbje712931ipd6i5uxam8'}
we can probably extract this string under the `res` folder?

2020-09-26 19:09 UTC, abdih commented on src/screens/splash/index.js
> +  constructor() {
💡 
your IDE is likely telling you that there is a deprecation with the usage around the `constructor` and `super`. this is simply telling you that the `super` should be called with only `props` and nothing else.

you may also be getting a warning related to `props` not being used, but I think this is an exceptional case where even though it's not being used, having it is actually preferred.

2020-09-26 19:09 UTC, abdih commented on src/screens/mapbox/index.js
> +    super();
💡

2020-10-04 19:14 UTC, abdih requested changes
minor requests

2020-10-04 19:14 UTC, abdih commented on src/res/index.js
> +  strings,
no trailing commas.

2020-10-04 19:14 UTC, abdih commented on src/screens/mapbox/index.js
> +import config from 'tinytown/config';
we spoke about this earlier, but please make sure to remove the android-related prompt notifying the user that their location will be tracked. thank you.

2020-10-10 22:18 UTC, keedyc reviewed
This all looks good to me, @alfalcon90.

Just one question. I see in issue #41 that you were interested in using the R namespace. Is that still of interest?

2020-10-10 23:14 UTC, alfalcon90 commented
I think we were using the R namespace for something else so I didn't want to break anything but now I can't find it so that might've changed since the mapbox refactor.

2020-10-13 18:18 UTC, merged