i36: App Bar
Tinytown/tinytown-react-app pull request #49
Opened 2020-10-10 00:56 UTC by alfalcon90

Fixes #36 

### Issues
- [ ] The way that RN scales things on Android seems to be off. On my phone, everything is scaled up by 2.75 instead of 3.0. This is creating some alignment issues with the avatar and the dark background. 
- [ ] The iOS simulator is not showing images. Probably related to this: https://github.com/facebook/react-native/issues/29279#issuecomment-658244428

2020-10-12 18:03 UTC, alfalcon90 commented
The AppBar component has two variations now: **MapBar** and **NavBar** (default). 
You can switch between them using the 'type' prop. Ex: `<AppBar type='map'/>`

![Oct-12-2020 10-39-36](https://user-images.githubusercontent.com/56562400/95776989-333b4d80-0c7a-11eb-8ed9-a0d6fbf0b2ce.gif)

2020-10-14 00:53 UTC, alfalcon90 commented
![Oct-13-2020 17-52-46](https://user-images.githubusercontent.com/56562400/95931026-f4da8700-0d7c-11eb-9dff-6568526ca633.gif)

2020-11-17 04:20 UTC, alfalcon90 commented on src/library/components/AppBar.js
> +      return <NavBar {...props} />;
Suggestion from Hami:

```
 const Component = props.type === 'home' ? HomeBar : NavBar;
  return <Component {...props} />;
```

2020-11-17 04:20 UTC, alfalcon90 commented on src/library/utils/normalize.js
> +        normalizedStyles[key][property] = styles[key][property];
Suggestion from Hami:
"I think using Ramda you can make this much more readable:"
```
const isNumber = R.is(Number);
const isInTarget = targetProperties.includes(property);
const propertyToNormalize = (property, value) => isInTarget(property) && isNumber(value);
R.map(
  properties => R.mapObjIndexed((property, value) => propertyToNormalize(property, value) ? normalize(value) : value,  properties),
  styles
)
```

2020-11-17 04:20 UTC, alfalcon90 commented on src/res/svg/index.js
> +Platform.OS === 'android'
Leftover from previous iteration, to be removed

2020-11-17 16:27 UTC, alfalcon90 commented on src/res/svg/index.js
>  import React from 'react';
Fixed. This is much better, thanks for the tip @abdih !

2020-11-21 20:58 UTC, abdih requested changes

2020-11-21 20:58 UTC, abdih commented on src/library/components/index.js
> +}
✏️
inspiration from https://stackoverflow.com/questions/34072598/es6-exporting-importing-in-index-file
```suggestion
export {default as AppBar} from './AppBar';
export {default as FAB} from './FAB';
export {default as IconButton} from './IconButton';
export {default as Menu} from './Menu/MenuContainer';
export {default as MenuDivider} from './Menu/MenuDivider';
export {default as MenuItem} from './Menu/MenuItem';
```

2020-11-21 20:58 UTC, abdih commented on src/library/utils/normalize.js
> +  return size;
it generally is bad practice to overwrite the function parameter. why not just return the expression directly?

2020-11-21 20:58 UTC, abdih commented on src/library/utils/normalize.js
> +import * as R from 'ramda';
you can just import the methods you need: `import {mapObjIndexed, is, map} from 'ramda';` 🐱

2020-11-21 20:58 UTC, abdih commented on src/library/utils/normalize.js
> +  const isNumber = R.is(Number)
if you decide to follow 🐱 , then you can remove the Object/Method notation around 'R' and use the expression directly here and elsewhere below.

2020-11-21 20:58 UTC, abdih commented on src/res/svg/index.js
> +}
I think you can use suggestion from ✏️ here, too

2020-11-21 20:58 UTC, abdih commented on src/screens/mapbox/index.js
> +
I don't have strong feelings about this and I'm not recommending doing this exhaustively for every file right now, but I think since we don't currently have a strong established convention for how to separate imports to achieve proper semantic segregation, we should keep all lines together to avoid accidentally implying a grouping where there really isn't one.

2020-11-21 21:48 UTC, alfalcon90 commented on src/library/components/AppBar.js
> +// HomeBar - Used in the Home Screen
I'm gonna go ahead and split this into two components, I don't think it makes sense to keep them together.

2020-11-21 21:53 UTC, alfalcon90 commented on src/library/components/AppBar.js
> +  state = { showingMenu: false };
I think I'll refactor this using a function component.

2020-11-21 21:57 UTC, alfalcon90 commented on src/library/components/index.js
> +}
Ha this was actually on my to-do list. I found out about it a few days ago when I was on the ecmascript website

2020-11-21 23:50 UTC, alfalcon90 commented on src/library/components/AppBar.js
> +// StyleSheet
These were useful when I had no idea what was going on inside these files due to not knowing anything about React.

2020-11-22 00:02 UTC, alfalcon90 commented on src/library/utils/normalize.js
> +import * as R from 'ramda';
What about the functions below? 
`const { cond, T: otherwise, identity, always } = R;`

2020-11-22 02:28 UTC, abdih commented on src/library/utils/normalize.js
> +import * as R from 'ramda';
oh didn't notice those ones. I think you can consolidate all of them on the import line; the only tricky one might be 'T: otherwise', which I think you might have to change to `import {mapObjIndexed, ..., T as otherwise, ....} from 'ramda'`. I'm not sure though; please double check the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) for syntax concerning imports in es6.

2020-11-22 02:30 UTC, abdih approved these changes
aside from [this](https://github.com/Tinytown/tinytown-react-app/pull/49#discussion_r528271111), lgtm.

2020-11-22 03:15 UTC, alfalcon90 commented on src/res/svg/index.js
> +}
I believe this is the only todo left here. Can you clarify the meaning of ✏️  here?

2020-11-22 06:32 UTC, abdih commented on src/res/svg/index.js
> +}
the emoji is a reference to [another comment](https://github.com/Tinytown/tinytown-react-app/pull/49#discussion_r528240426) I had made in the same batch of review -- unfortunately, GitHub doesn't allow cross-comment linking while doing 1 batch of review, so I have to invoke some "clever" work-around.

does that make sense?

2020-11-22 16:26 UTC, alfalcon90 commented on src/res/svg/index.js
> +}
gotcha, there's only one export in this case, though.

2020-11-22 18:50 UTC, alfalcon90 commented on src/res/svg/index.js
> +}
synced offline

2020-11-22 18:52 UTC, jamullan approved these changes

2020-11-22 18:59 UTC, abdih approved these changes

2020-11-22 19:29 UTC, merged