Feature/i37 settings menu
Tinytown/tinytown-react-app pull request #50
Opened 2020-10-11 00:11 UTC by keedyc

Fixes #37 

Just a few minor notes:
* I forgot to preface my commits with "i37". Will remember that for next time 😅
* I haven't worked with SVGs much, so I have no idea whether I added them correctly.
* For now, clicking **Sign Out** or **About** just logs a message to the console.

2020-10-11 01:14 UTC, alfalcon90 approved these changes
LGTM. I removed `fill="none"` from the SVGs so that it matches the ones in #49 when we merge all of these.

2020-10-11 22:50 UTC, alfalcon90 submitted a review, later dismissed

2020-10-24 21:33 UTC, abdih requested changes
unfortunately, I didn't have time to fully get through the review today due to other commitments, but I'm submitting my requested changes up until the point I did manage to review.

overall, things look good, and I know I'm being demanding, but it's all with the intention of having a solid codebase!

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +const SCREEN_INDENT = 8;
capitalizing named constants in javascript is really not necessary given the `const` modifier.

furthermore, please remove trailing commas, as this doesn't comply with [our current coding style](https://github.com/Tinytown/tinytown-react-app/pull/10#discussion_r456794877). as a matter of fact, could you please modify CONTRIBUTING.md in this same PR to mention this under Code Style to notify future developers of both the trailing comma and named constants. thanks.

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +  _container = null;
+:1 for adding `_` for private attributes of a class. I'd advise adding this to the CONTRIBUTING.md, too. I think myself and others should adopt it, too.

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +  _onMenuLayout = (e) => {
not necessary to use parenthesis when there's only 1 parameter.

since this is the third item I'm writing a style-related comment, I really think it's about time that we formalize our eslint rules.

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +    });
how about extracting this into another function called `resetState()` and getting rid of the comment?

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +      (!isRTL && left + menuWidth > windowWidth - SCREEN_INDENT)
these conditions are a bit complicated. I'd advise breaking them apart into named constants that helps with readability. for instance, I'm not exactly sure what the plain English description of what `(isRTL && left + buttonWidth - menuWidth > SCREEN_INDENT)` evaluating to true means.

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +      });
perhaps, it'd help to introduce a helper function `flipX` and `flipY`, and then 
```suggestion
    const hitsBottomBorder = top > windowHeight - menuHeight - SCREEN_INDENT;
    if (hitsBottomBorder) {
      transforms.push({
        translateY: flipY(menuSize), <-- or menuSizeAnimation.y, but please see comment 🐃 
      });
```

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +        translateX: Animated.multiply(menuSizeAnimation.x, -1),
🐃  At this point, I haven't read through the entire changes, but I think dealing with 1 layer of abstraction as opposed to two is easier, so since we seem to put in work to create 'menuSize', why not use it (i.e., `menuSize.width`)?

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +      ...(isRTL ? { right: left } : { left }),
this isn't entirely switching right for left and left to right, since `{ right: left }`, left would still presumably still be `left`.

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +============================================================================= */
🐶 
comments like this clutter the code unnecessarily. please remove. if you really want to provide a separation, I'd advise moving this to another file next to this component (i.e., `Menu.styled.js`), in a directory next to it (i.e., `styles/index.js`), or somewhere else that's reasonable and importing it.

2020-10-24 21:33 UTC, abdih commented on src/library/components/Menu.js
> +============================================================================= */
🐶

2020-10-24 21:33 UTC, abdih commented on src/library/components/MenuDivider.js
> +This component is a customized version of the Menu Divider component from react-native-material-menu [https://github.com/mxck/react-native-material-menu].*/
🔢 
we don't need to clutter our codebase with where you've drawn the inspiration. I'm not a legal expert, but I'm fairly confident that by copying-and-pasting parts of the code and modifying it here, you are not committing any legally implicating behavior.

2020-10-24 21:33 UTC, abdih commented on src/library/components/MenuItem.js
> +/* Menu Item Component
🔢

2020-10-24 21:33 UTC, abdih commented on src/library/components/MenuItem.js
> +============================================================================= */
🐶  -- from this point forward, I'm not going to comment on every other place where this applies; please use your judgement and remove accordingly.

2020-10-24 21:33 UTC, abdih commented on src/library/components/MenuItem.js
> +    overflow: 'hidden'
another style-related comment. please be consistent in quotes and stick to single-quotes.

2020-10-24 21:33 UTC, abdih commented on src/res/colors.js
> +export const disabled = 0.4;
I think this should justify a JSON object because in the future, we might want to specify transparency levels for other things than just when something's disabled. now, the question is do we also want other attributes for when a button is `disabled` and if so, then I think we should have an object for `disabled`, in which `transparency` is an attribute of it.

2020-10-25 05:08 UTC, abdih commented on src/res/svg/index.js
>  const Icon = props => {
nit, but I think the following looks cleaner, since I personally don't like switch-case statements -- they literally require more code as a function of items than otherwise (e.g., they at least require 1 `return` per item):

```
const Icons = {
    crosshairs: CrosshairsIcon,
    info: InfoCircleIcon,
    megaphone: MegaphoneIcon,
    signout: SignOutIcon,
    twitter: TwitterIcon
};
const Icon = props => {
    const ValidatedIcon = Icons[props.icon] || PlaceholderIcon;
    return <ValidatedIcon {...props} />;
}
```

2020-10-25 19:00 UTC, alfalcon90 commented on src/library/components/Menu.js
> +const SCREEN_INDENT = 8;
I like the thinking behind using trailing commas to avoid messy git diffs: https://github.com/airbnb/javascript#commas--dangling

I updated the CONTRIBUTING.md file to reflect this and the named constant.

2020-10-25 19:03 UTC, alfalcon90 commented on src/library/components/Menu.js
> +  _onMenuLayout = (e) => {
I like Airbnb's reasoning for including parentheses: https://github.com/airbnb/javascript#arrows--one-arg-parens

I added it to our ESLint rules

2020-10-25 19:03 UTC, alfalcon90 commented on src/library/components/MenuDivider.js
> +This component is a customized version of the Menu Divider component from react-native-material-menu [https://github.com/mxck/react-native-material-menu].*/
SG!

2020-10-25 19:09 UTC, alfalcon90 commented on src/res/svg/index.js
>  const Icon = props => {
This is sweet. I actually changed the switch-case statement to an IF in the App Bar [branch](https://github.com/Tinytown/tinytown-react-app/pull/49/files#diff-f4702cb425c6fe9463ff90bcf8b706ef63ece2251178a9c0906525d82cea0c44) to support returning different icons depending on Platform so let's move this over there and change it on that one.

2020-10-25 22:05 UTC, alfalcon90 commented on src/res/colors.js
> +export const disabled = 0.4;
Changed it to this for now
```
export const opacity40 = {
  opacity: 0.4,
};
```

2020-10-31 20:19 UTC, abdih commented on src/library/components/Menu.js
> +        translateX: Animated.multiply(menuSizeAnimation.x, -1),
looking at this more closely, I'm not sure the math here makes sense to me; could you please provide some justification? (in fact, moving forward, I think a comment here would be useful for future developers.)

the reason I say the math doesn't entirely make sense to me is because, if I consider the second case of the condition (i.e., `!isRTL && left + menuWidth > windowWidth - screenIndent` as **_when the screen isn't right-to-left (e.g., the user is using English as opposed to, say, Arabic) and the horizontal end of the menu (i.e., its start (i.e., left) plus its width (i.e., menuWidth)) is past the allotted space (i.e., windowWidth - screenIndent)_**, I don't understand what translating the X according to `Animated.multiply(menuSizeAnimation.x, -1)` is supposed to do, let alone why it's correct.

2020-10-31 20:26 UTC, abdih commented on src/library/components/Menu.js
> +    const { testID, button, style, children } = this.props;
+:1 for testID!

2020-10-31 20:43 UTC, abdih commented on src/library/components/Menu.js
> +          }
the way `hide` is handled is quite awkward.

- there's at least 1 unnecessary level of indirection: `_hide` simply calls `hide`. `hide` doesn't seem necessary.
- there's inconsistency in naming (e.g., hide and onHidden, which I think would better be named as onHide, but even then, again, still, I don't think this inconsistency should exist)
- `onHidden` seems to never be used, and furthermore, I don't get why it's necessary. (I do admit that a visual component callback may be broken down into two separate callbacks, one internal to the component itself and one external, but if the latter is necessary, that's usually what the callback on the prop is for (e.g., this.props.onHide).
- while, distinguishing between the platforms is not entirely bad in and of itself, there's virtually no explanation in a comment why that's necessary and why we only call the external callback when the platform isn't ios.

2020-10-31 20:55 UTC, abdih commented on src/library/components/Menu.js
> +      (isRTL && left + buttonWidth - menuWidth > screenIndent) ||
assuming this condition is a mirror of the latter condition after the `||` and I interpreted the intent of the second condition correctly that it's trying to handle a case where the menu is too far _right_, in the case after the '||', then this should be concerned with checking if the menu is too far _left_. in that case, I'm not sure how this check is doing that exactly.

the strange thing is that this is working somehow as per the original inspiration (https://github.com/mxck/react-native-material-menu#readme), so technically, it's ok, but I do think understanding it better might allow us to simplify it to something like (left < screenIndent).

2020-10-31 21:03 UTC, abdih commented on src/library/components/Menu.js
> +  _onMenuLayout = (e) => {
I think we can just rename this method to `startMenuAnimation` and remove the comment.

2020-10-31 23:48 UTC, abdih commented on src/library/components/Menu.js
> +      (isRTL && left + buttonWidth - menuWidth > screenIndent) ||
agreed with @keedyc for the sake of simplicity, we will simply assume that RTL is always false. furthermore, added clarifying comments regarding animation transformations.

2020-11-01 01:15 UTC, abdih commented on src/screens/mapbox/index.js
> +  };
this should be done through changing passed in prop to the menu component and with maintaining the state in the mapbox component.

2020-11-02 23:17 UTC, alfalcon90 submitted a review, later dismissed

2020-11-02 23:17 UTC, alfalcon90 commented on src/screens/mapbox/index.js
> +  };
Is this and line 258 needed still? Seems to be working fine without it but I'm not sure if I'm breaking something.

2020-11-09 03:04 UTC, abdih approved these changes

2020-11-09 03:15 UTC, alfalcon90 commented on src/screens/mapbox/index.js
> +    const { zoomLevel, followUser, haveLocationPermission, goingToLocation, cameraCoordinates, heading, showingMenu } = this.state; // eslint-disable-line max-len
Do you want to remove the max-len rule from the .eslintrc.js file?

2020-11-17 04:03 UTC, alfalcon90 approved these changes

2020-11-17 04:05 UTC, merged