i45: Onboarding Navigation
Tinytown/tinytown-react-app pull request #53
Opened 2020-10-14 02:19 UTC by alfalcon90

Fixes #45

2020-10-18 18:46 UTC, alfalcon90 commented
This is what's currently implemented in onboarding/index.js right now.

![Oct-18-2020 11-44-25](https://user-images.githubusercontent.com/56562400/96377037-7e040c00-1137-11eb-85c0-473608465cb9.gif)

2020-10-18 18:48 UTC, alfalcon90 commented on src/screens/onboarding/index.js
> +            { !this.state.isLocated && <FAB label={R.strings.button.gotoLocation} theme='green' icon='crosshairs'
TODO: Call the gotoLocation() function in components/Map.js from onboarding/location.js. 
If successful then -> this.setState({isLocated: true}) to switch FABs

2020-10-18 18:49 UTC, alfalcon90 commented on src/screens/onboarding/index.js
> +              onPress={() => this.setState({isLocated: true})}/> }
TODO: Call the gotoLocation() function in components/Map.js from onboarding/location.js. 
If successful then -> this.setState({isLocated: true}) to switch FABs

2020-10-18 18:51 UTC, alfalcon90 commented on src/screens/onboarding/index.js
> +                  console.log(e.message);
Fix Twitter functionality then -> navigate to Home Screen

2020-12-13 22:00 UTC, abdih requested changes
I'm impressed with the level of contribution here; there is a lot of good stuff here.

I didn't get a chance to go through the entire PR because truthfully, I'm a bit mentally exhausted, but I do think I've raised some meaningful concerns.

Looking forward to working with you to fix some of them!

2020-12-19 19:04 UTC, alfalcon90 commented on App.js
> +    getData('userLocation').then((location) => {
Correct. isSignedIn gets updated (or not if the user is not signed in) by the call to the firebase library on line 31. Firebase handles their own state persistence as we discussed in our last chat so we don't store auth state in our own local storage.

2020-12-19 19:12 UTC, alfalcon90 commented on src/library/components/TwitterAuth.js
> +      auth().onAuthStateChanged((user) => (user ? props.signIn(user) : null))
This handles when the user first taps on the "Log in with Twitter" button. The one in App.js checks the auth state whenever the app launches.

2020-12-19 19:33 UTC, alfalcon90 commented on App.js
> +      subscriber; // unsubscribe on unmount
I'm following the Firebase docs here: https://rnfirebase.io/auth/usage#listening-to-authentication-state
On closer inspection, what gets returned from calling `auth().onAuthStateChanged()` here is: `return () => subscription.remove();`

2020-12-19 19:47 UTC, alfalcon90 commented on src/library/components/WorldMap.js
> +  const cameraRef = useRef(null)
I thought we had an ESLint rule for it but somehow we never added one. Added rule and ran linter to fix all of these.

2020-12-19 19:57 UTC, alfalcon90 commented on src/library/apis/geolocation.js
> +let watchId = null;
(1) We need the ID to be able to call `Geolocation.clearWatch(watchId)` in **stopWatchingLocation()**. It only gets used locally in this file so it doesn't really belong in the redux store, BUT it gets used in both **watchLocation()** and **stopWatchingLocation()** so that's why it's outside both functions.

2020-12-19 21:32 UTC, alfalcon90 commented on src/library/apis/geolocation.js
> +      watchId = Geolocation.watchPosition(
It took me a bit to remember why I did this in a strange way with two variables instead of one. The geolocation library starts with an ID of 0, which returns false when used in that if statement and you end up with two instances of **watchPosition()**.

2020-12-19 21:39 UTC, alfalcon90 commented on src/library/apis/storage.js
> +  }
I tried it at first but the description of it here scared me away: https://react-native-async-storage.github.io/async-storage/docs/api#clear

2020-12-19 21:40 UTC, alfalcon90 commented on src/library/components/HomeBar.js
> +  photoURL: state.auth.user?.photoURL,
We should be good for React Native, right?

2020-12-19 21:51 UTC, alfalcon90 commented on src/library/components/WorldMap.js
> +  useEffect(() => {
Found this: https://reactjs.org/docs/hooks-effect.html#tip-use-multiple-effects-to-separate-concerns

2020-12-19 21:52 UTC, alfalcon90 commented on src/library/components/WorldMap.js
> +        onDidFinishRenderingMapFully={!props.appState.loaded.map ? () => mapLoadingHandler(true) : null}
It's confusing to me and I wrote it. I'll take a stab at refactoring.

2020-12-20 20:46 UTC, abdih requested changes

2020-12-20 20:46 UTC, abdih commented on App.js
> +const mapStateToProps = (state) => ({ isSignedIn: state.auth.isSignedIn })
🍎

2020-12-20 20:46 UTC, abdih commented on App.js
> +    getData('userLocation').then((location) => {
the first part of what you're saying is true

> isSignedIn gets updated (or not if the user is not signed in) by the call to the firebase library on line 31

, but this part is not entirely accurate in representing the current implementation because as I'll elaborate in just a moment, (i) you are indeed storing auth state in our own local storage and (ii) you are redundantly telling firebase to do this storage.

> Firebase handles their own state persistence as we discussed in our last chat so we don't store auth state in our own local storage.

(i) on the line with 🍎 , you are saying that this component should be passed a property `isSignedIn` that is coming from our local storage: `state.auth.isSignedIn`

(ii) on the line with 🐱 , you are instructing how firebase should manipulate our local storage.

this flow to me is incorrect for at least 1 reason: if the user's login status changes, it will cause (ii) to be executed once more, since this component re-renders whenever mapStateToProps leads to a different result. In other words, you re-instruct how firebase should manipulate our local storage every time the user's login status changes, even though the instruction on _how_ firebase should manipulate the local storage doesn't change (i.e., firebase should still still listen to the auth state of the user and respectively set `state.auth.isSignedIn` to _true_ or _false_ based on that state).

Given the above, I see 1 change that I think we should act on now: the code for line (ii) should be moved 1 layer up to AppContainer, where the provider is specified.

The other change is one that I'm not sure is worth pursuing at this moment, but I'll express my thoughts on:

The react-redux library seems to essentially _force_ our hand to not be able to use `getData` as a means to construct the `props` for this component in `mapStateToProps` because this method is asynchronous in nature and according to the specifications of this library, this [isn't allowed in connect](https://react-redux.js.org/using-react-redux/connect-mapstate#mapstatetoprops-functions-should-be-pure-and-synchronous). This is not ideal to me because I'm not convinced there's any meaningful difference between the accessor for `isSignedIn` and `getData('userLocation')`, aside from the latter being a retrieval from an asynchronous variation of the local state (i.e., @react-native-async-storage/async-storage) and the former a synchronous one (i.e., rdx/store).

2020-12-20 20:50 UTC, abdih commented on src/library/components/WorldMap.js
> +  useEffect(() => {
There's a nuance here with the link you're referencing; `useEffect` does _not_ seem to specify any indication of when the effect should occur, where as in the link you referenced, the different methods have well-defined, segregated occurrences in the lifecycle of a component's rendering: https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/

2020-12-20 20:52 UTC, abdih commented on src/library/components/WorldMap.js
> +  useEffect(() => {
unless, the conditions inside these different effects essentially simulate the different canonical methods of a component, which I can see since you do use for instance `isMounted` in `App launches || quits`.

tl;dr: I'm convinced that this isn't a blocker and your comments above the `useEffects` are ok. I'm resolving this thread.

2020-12-20 20:54 UTC, abdih commented on App.js
> +    getData('userLocation').then((location) => {
writing this as a request for pause on analyzing the above comment in the case I'm interpreting the line 🐱  incorrectly given your comment [here](https://github.com/Tinytown/tinytown-react-app/pull/53#discussion_r546272415).

2020-12-20 21:11 UTC, abdih commented on App.js
> +      subscriber; // unsubscribe on unmount
the returned value that you've made explicit is not in contention with my original suggestion, since it's implying that `auth().onAuthStateChanged()` in fact returns an _unsubscriber_ -- this also implies that the variable is currently not named correctly. furthermore, the function that's returned in `useEffect`, according to the [docs](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1) sounds like is what will be used to clean up the component when it essentially unmounts. it's fine to technically unsubscribe listening to data about the user's login status once this component is unmounted, but that unsubscriber method should come in as a prop from AppContainer to also accommodate [this](https://github.com/Tinytown/tinytown-react-app/pull/53/files/851d5e428cbcbdb860a9e2adb71a8024788be156#r546434172) comment.

2020-12-20 21:11 UTC, alfalcon90 commented on src/library/components/WorldMap.js
> +        onDidFinishRenderingMapFully={!props.appState.loaded.map ? () => mapLoadingHandler(true) : null}
Removed since it was no longer necessary.

2020-12-20 21:13 UTC, abdih commented on src/library/components/TwitterAuth.js
> +      auth().onAuthStateChanged((user) => (user ? props.signIn(user) : null))
I think there's some conflation here between subscription of the local state to firebase's data on the user's login status and the check against such a status. I think the subscription should happen in one place and at the AppContainer, with the relevant data flowing to components through mapStateToProps, and then inside various components, having the check against the respective attribute on that component's props.

please see [this](https://github.com/Tinytown/tinytown-react-app/pull/53/files/851d5e428cbcbdb860a9e2adb71a8024788be156#r546436931) comment for more context.

2020-12-20 22:06 UTC, alfalcon90 commented on src/library/components/TwitterAuth.js
> +      auth().onAuthStateChanged((user) => (user ? props.signIn(user) : null))
Ah this makes sense now. At some point, I think the instance in App.js was behind an if statement that prevented it from running all the time but yeah in this case we shouldn't need the second in TwitterAuth.js. I'll give it a shot. 

Should I move the location block right above it to AppContainer as well since it's basically doing the same thing but for user's location? I spent a lot of time trying to make this part of the redux/store.js code since it's basically setting the initial state of the store but there was no way out of async hell that I could figure out.

2020-12-20 22:33 UTC, alfalcon90 commented on src/library/components/TwitterAuth.js
> +      auth().onAuthStateChanged((user) => (user ? props.signIn(user) : null))
Fixed in a0b2a04

2020-12-20 23:20 UTC, alfalcon90 commented on App.js
> +      subscriber; // unsubscribe on unmount
The documentation that you get in VSCode for `onAuthStateChanged` has an example with your name recommendation and the actual method being called so maybe the example on the website is out-of-date. 
![Screen Shot 2020-12-20 at 3 17 23 PM](https://user-images.githubusercontent.com/56562400/102726833-9d095080-42d6-11eb-9d92-52d11abb5d60.png)

2020-12-20 23:36 UTC, abdih commented on src/library/components/WorldMap.js
> +        props.updateUserVisible(res.userVisible);
usage of `updateUserVisibile` here and in a couple other places seems to disagree with the convention established in using a reducer in other parts of this change-set (e.g., store.dispatch(<function that'll return an action>(...)) or, for asynchronous local state interactions, using a method that has method signature `() => async (dispatch) => <returns action>`).

2020-12-20 23:51 UTC, abdih commented on src/redux/actions/types.js
> +export const APP_STORAGE = 'app_storage';
I think technically using [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) is more rigorous here as it avoids accidental or mal-intentioned creation of an action.

2020-12-20 23:56 UTC, abdih commented on src/redux/actions/types.js
> +export const APP_STORAGE = 'app_storage';
I think technically using [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) is more rigorous here as it avoids accidental or mal-intentioned creation of an action.

2020-12-20 23:59 UTC, abdih commented on src/library/components/HomeBar.js
> +  photoURL: state.auth.user?.photoURL,
you're absolutely correct here; it looks like it's fully supported for react native: https://medium.com/bsadd/optional-chaining-in-react-native-805a374788d3

2020-12-24 10:16 UTC, abdih commented
just pulled to checkout what the app looks like on the simulator for iOS, and it looks like (i) I'm unable to pinch, zoom, or pan, and (ii) when I rotate the device, it's as if the map rotates with the screen, which I don't believe is correct -- if I rotate the device so it's landscape right while the north side of the map is pointing to the north of SF, when the rotation is complete, I expect north to be in the 'up' direction still, even though the device's top is on the right.

2020-12-25 02:43 UTC, alfalcon90 commented on src/library/apis/geolocation.js
> +      watchId = Geolocation.watchPosition(
Moved to useLocation hook in f12ea60

2020-12-25 02:43 UTC, alfalcon90 commented on src/library/apis/geolocation.js
> +let watchId = null;
Moved to useLocation hook in f12ea60e9dc2e844d8f7c9d51f72c115c1268416

2020-12-25 02:45 UTC, alfalcon90 commented on src/library/components/Scrim.js
> +    marginTop: -40,
Fixed in d6b4a21b35dbb884efc52cf81704873c35f94dd7

2021-01-03 21:40 UTC, alfalcon90 commented
Pushed the last set of fixes and improvements, all set for reviews.

2021-01-07 22:21 UTC, abdih requested changes

2021-01-07 22:21 UTC, abdih commented on src/library/components/HomeBar.js
>    const [showMenu, setShowMenu] = useState(false);
🧨

2021-01-07 22:21 UTC, abdih commented on src/screens/OnboardingScreen.js
> +  const [authLoading, setAuthLoading] = useState(false);
🧨 
if it isn't there already and there's a good justification for this, could you please add to the CONTRIBUTING document what the convention is when we're supposed to use `useState` directly inside a component versus when we're supposed to use a more indirect approach (e.g., useMap) through _library/hooks_.

2021-01-10 21:28 UTC, alfalcon90 commented on src/library/hooks/useAppLaunch.js
> +    dispatch(getStateFromLS());
I'm a little confused, do you mean the first arrow function in `useEffect(() => {}` or the arrow function in the `getStateFromLS` declaration in appState.js?

2021-01-10 21:35 UTC, alfalcon90 commented on src/library/components/WorldMap.js
> +const WorldMap = ({ userLocation, updateUserLocation, updateUserVisible, children }) => {
They're referencing the same function, they get passed as props down at the bottom by the connect function and then destructured here. https://react-redux.js.org/api/connect

2021-01-10 21:54 UTC, alfalcon90 commented on src/screens/OnboardingScreen.js
> +  const [authLoading, setAuthLoading] = useState(false);
Looking at the [React Hooks](https://reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook) documentation it looks like the general rule of thumb is similar to any other function: "When we want to share logic between two JavaScript functions, we extract it to a third function". That's the case for useMap and useLocation. The other reason (which applies to useAppLaunch) is less about reusability and more about readability and keeping components focused on UI rendering while hooks handle the logic. I'll write up a version of this comment in the CONTRIBUTING file for future reference.

2021-01-18 21:54 UTC, merged